export const MARKETPLACE_PROS = {
  ayanfe: {
    name: 'Ayanfe Buildings',
    trade: 'Engineer',
    category: 'Engineering',
    rating: '4.9',
    jobs: '126 completed jobs',
    price: 'Quote or hourly',
    response: 'Replies in 12 min',
    badge: 'Verified',
    about: 'Structural, repair, and small build work with clean quotes and documented job completion.',
    services: ['Repairs', 'Installations', 'Site assessment', 'Quotes'],
  },
  plumbing: {
    name: 'Northside Plumbing',
    trade: 'Plumber',
    category: 'Plumbing',
    rating: '4.8',
    jobs: '89 completed jobs',
    price: 'From $85/hr',
    response: 'Replies in 18 min',
    badge: 'Fast reply',
    about: 'Leaks, fixture replacements, emergency plumbing, and preventative maintenance.',
    services: ['Leaks', 'Fixtures', 'Drainage', 'Emergency calls'],
  },
  electric: {
    name: 'BrightLine Electric',
    trade: 'Electrician',
    category: 'Electrical',
    rating: '4.7',
    jobs: '73 completed jobs',
    price: '$90/hr',
    response: 'Replies in 25 min',
    badge: 'Verified',
    about: 'Residential electrical installs, troubleshooting, panel work, and outdoor power.',
    services: ['Outlets', 'Lighting', 'Panel work', 'Troubleshooting'],
  },
  hair: {
    name: 'Amina Hair Studio',
    trade: 'Hairstylist',
    category: 'Hair',
    rating: '4.9',
    jobs: '141 completed bookings',
    price: 'From $80/session',
    response: 'Replies in 9 min',
    badge: 'Fast reply',
    about: 'Cuts, installs, styling, and event hair with clear session pricing and quote-based custom work.',
    services: ['Hair styling', 'Braids', 'Installs', 'Event styling'],
  },
  tailor: {
    name: 'Precision Tailoring',
    trade: 'Tailor',
    category: 'Tailoring',
    rating: '4.8',
    jobs: '64 completed jobs',
    price: 'Quote first',
    response: 'Replies in 22 min',
    badge: 'Available',
    about: 'Alterations, repairs, fittings, and custom garment work priced after request details.',
    services: ['Alterations', 'Repairs', 'Fittings', 'Custom work'],
  },
  mechanic: {
    name: 'Krown Auto Care',
    trade: 'Mechanic',
    category: 'Auto',
    rating: '4.7',
    jobs: '58 completed jobs',
    price: 'From $95/hr',
    response: 'Replies in 31 min',
    badge: 'Mobile service',
    about: 'Diagnostics, minor repairs, brakes, batteries, and mobile inspection support.',
    services: ['Diagnostics', 'Brakes', 'Battery', 'Mobile inspection'],
  },
} as const;

export type MarketplaceProId = keyof typeof MARKETPLACE_PROS;

export const MARKETPLACE_PRO_LIST = Object.entries(MARKETPLACE_PROS).map(([id, pro]) => ({
  id: id as MarketplaceProId,
  ...pro,
}));
